#!/usr/bin/env python
# coding: utf-8

# #### Problem 2:
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# In[1]:


first, second, summed = 1, 1, 0
final_sum = 0
while summed < 4000000:
   summed = first + second      
   if summed%2 == 0:
       final_sum = final_sum + summed
   first = second
   second = summed
print(final_sum)


# In[ ]:




